### ISSUE TITLE
`sd a0,-24(s0)` is assembled as `sd a0,24(s0)` (negative offset treated as positive)

### ISSUE THREAD

**Issue by tmcintos** [Mariotti94/WebRISC-V#10]
`sd a0,-24(s0)` is assembled as `sd a0,24(s0)` (negative offset treated as positive).  In contrast, a negative offset in a load instruction is handled correctly. e.g.

`sd a0,-24(s0)`
`ld a0,-24(s0)`

is loaded into instruction memory as:

`sd a0,24(s0)`
`ld a0,-24(s0)`

**Comment by Mariotti94** [comment]
Thank you for bringing this bug to my attention, it has been fixed.

**Comment by tmcintos** [comment]
Confirmed. Thanks!
