### ISSUE TITLE
Is website broken?

### ISSUE THREAD

**Issue by valerionew** [Mariotti94/WebRISC-V#12]
Hi, i wanted to see the online version of the simulator, but currently [the page](http://www.dii.unisi.it/~giorgi/WebRISC-V) is giving "ERR_CONNECTION_RESET".

Is it offline or it's just me?

**Comment by Mariotti94** [comment]
Hello, thank you for your interest.

It is not offline, just in case, here is where [the page](http://www.dii.unisi.it/~giorgi/WebRISC-V) should redirect you to: [direct link](http://x.dii.unisi.it:8098/~giorgi/WebRISC-V/index.php).

Let me know if you manage to access it.

**Comment by valerionew** [comment]
Sorry for not letting you know.
I can confirm it's working correctly, it was just the university firewall blocking that port.
Thanks!
