### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by zidingz** [Mariotti94/WebRISC-V#13]
Hey there!

I belong to an open source security research community, and a member (@hitisec) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Mariotti94** [comment]
Hello, thank you for bringing this to my attention.

Opening the simulator, under the logo on the top-left it is possible to find an email for direct contacts.
It may be difficult to see, so i have added the `SECURITY.md` file, as requested: inside it you can easily find that same email.

Thanks for your help, i'll be waiting for the report.

EDIT: Issue resolved.
