### ISSUE TITLE
Weird behaviour with simple code

### ISSUE THREAD

**Issue by smarco** [Mariotti94/WebRISC-V#16]
The following code depics a weird behaviour on execution:

```
.data
datoprueba: .word 777
.text
la s1, datoprueba
lw s1, 0(s1)    #
nop    #
bge s1, s1, end    #
end:
```

```
Instruction       1 2 3 4 5 6 7 8 9
auipc s1, 0       F D X M W
addi s1, s1, 1024   F D X M W
lw s1, 0(s1)          F D X M W
addi x0, x0, 0          F D X M W
bge s1, s1, 8             F D X M W 
```

Seems not intuitive that the BGE effectively decodes (D) on cycle 6 because the input data (s1) is available at the end of cycle 6 (stage M of lw s1, 0(s1)).

Thanks in advance for the help.

**Comment by Mariotti94** [comment]
Hello, it is the correct behavior.
The data is written on the first half of the cycle (on the M stage), and read during the second half of the cycle (on the D stage).
You may read a more in depth explanation about the functioning of the pipeline on the chapter "The Processor" of the book "Computer Organization and Design RISC-V Edition", if you'd like to investigate further.

**Comment by Mariotti94** [comment]
EDIT: You are correct, i went back to read again the in depth explanation about the functioning of the pipeline on the chapter "The Processor" of the book "Computer Organization and Design RISC-V Edition", and checked the pipeline diagram again.

**Comment by smarco** [comment]
Well, I'm afraid I cannot say I fully understand the logic implemented within the simulator (and I would like to). In the seminal reference you have cited, it is clearly stated that: 

"By extension, if a load is immediately followed by a conditional branch that depends on the load result, two stall cycles will be needed, as the result from the load appears at the end of the MEM cycle but is needed at the beginning of ID for the branch." 

Then, I wanted to double-check to avoid wasting your time. So I check the same code on the winDLX. The result was that the stall cycle I was expecting appeared (I hope you can visualize the image).

![image](https://user-images.githubusercontent.com/2584429/140997642-bcf61156-bbdc-493b-aa61-b11c75a7c8e2.png)

Finally, according to your comment, I would like to point out that the model you propose would imply a critical path that executes the M stage (1 cycle) + write on the register file on D (1/2 cycle) + read the RF on D (1/2) + compare on D. At least, an increment of 2x on the clock cycle critical path.

Maybe the model you implement is making a different assumption. Perhaps there is something silly slipping my mind. Thank you for taking the time to evaluate my query and the patience to answer it. Apologies in advance if the question is too naive.

**Comment by Mariotti94** [comment]
Here are some excerpts from the previously mentioned book that mention this logic:
![Screenshot from 2021-11-09 21:51:18](https://user-images.githubusercontent.com/11044329/141003381-7130a313-334d-49d0-8c04-43f511d7a48e.png)

![Screenshot from 2021-11-09 21:53:05](https://user-images.githubusercontent.com/11044329/141003405-12dbf54b-41d2-4245-b3b2-3af2f8036fe0.png)

![Screenshot from 2021-11-09 21:54:57](https://user-images.githubusercontent.com/11044329/141003419-c112a03d-6e43-43da-b889-423dc4e26f29.png)

**Comment by smarco** [comment]
Moreover, to this issue, I can spot inconsistent behaviour between the 2 following examples:

Case 1 (without the nop in the middle): 2 cycles stall
![image](https://user-images.githubusercontent.com/2584429/141006130-ffac7bfd-569e-4697-9c8b-0e13ab3e9529.png)

Case 2 (with the nop in the middle): No stall
![image](https://user-images.githubusercontent.com/2584429/141006257-8b2bbe8e-12ea-4a36-bbe3-701950853cff.png)

Please note how case 1 behaves exactly like the Hennessy&Patterson states, and the case 2 is the bug I'm reporting here. Clearly two different strategies for the same situation.

**Comment by Mariotti94** [comment]
This inconsistency is, in fact, not ok.
Thank you for bringing this to my attention, i will look into it further over the next few days.

**Comment by smarco** [comment]
PS. I know, I mean, we all have read several times the Hennessy&Patterson (and different editions). Your simulator is a great tool for teaching too (that is why I would like to use it). Thanks for taking the time and solving the bug :-)

**Comment by Mariotti94** [comment]
Hello, you were correct about how the behaviour should be, i went back to reread the necessary section again and investigated upon my pipeline diagram (i should not reply to issues before checking my sources, if i don't remember too well 😅).
I have fixed this bug, the problem was a check in the Hazard Detection Unit that was missing.
Thanks again for the report, let me know if you find anything else weird.

PS: The live site is not yet updated, should be updated by tomorrow (you can easily check through the version number, top left under logo).
EDIT: Site updated.

**Comment by smarco** [comment]
Don't worry about it. Quite often, I too have a hard time spotting the errors when reviewing assignments on this :-)

Thanks so much for the quick reply and fix. 
I really appreciate it.
