### ISSUE TITLE
Branch stall bug

### ISSUE THREAD

**Issue by ashriram** [Mariotti94/WebRISC-V#17]
First off; thank you for this great teaching tool. 
I think there is a bug in the branch handling; 
See example below. When the branch is in the EX stage, the newPC is being calculated and is not available until 1 cycle later
. However in this case, the addi,a3,zero,0 is in the IF stage in the same cycle when the beq is in the EX stage.; shouldn't it be in the IF when the branch is in the MEM stage i.e., branch address is already calculated.
See ripes for reference. Ripes flushes both instructions that are following a taken branch.

```
add a2,a1,a0
beq a2,zero,L1
addi a3,zero,1
L1:
addi a3,zero,0
```

**Comment by Mariotti94** [comment]
Hello, thank you for the compliment.
The current behavior is correct, the data is ready at the EX stage.
The reason for this is the following: to reduce the delay of branches, the calculation and comparisons for them are done in the ID stage; this can be seen in WebRISC-V pipeline diagram, and is proposed on the chapter "The Processor -> Control Hazards" of the book "Computer Organization and Design RISC-V Edition".

**Comment by ashriram** [comment]
Got it.
What was confusing for me was that there was no adder shown in the ID stage to do PC+offset . It only said branch comparison box in the pipeline diagram.

Maybe if we just added an adder box it would be convenient. Obviously, it would need a line from PC and Immsel. 

H and P book.
"We already have the PC value and the immediate field in the IF/ID pipeline register, so we just move the branch adder from the EX stage to the ID stage; of course, the address calculation for branch targets will be performed for all instructions, but only used when needed."

What is confusing I think is Berkeley's own slides have the branch unit in the EX stage. https://cs61c.org/fa21/pdfs/lectures/lec14.pdf

**Comment by Mariotti94** [comment]
Actually, the adder units on the ID stage are present, you may just have missed them.
Here is a snippet of the pipeline in which i highlighted the relevant elements for branches found in the ID stage:
![branch_elements](https://user-images.githubusercontent.com/11044329/144729154-486c6bc3-d50b-45c9-9db3-8bee0ce4367e.png)

**Comment by ashriram** [comment]
Aah! Missed that completely

thanks
