### ISSUE TITLE
There is a bug about load a value from the data section.

### ISSUE THREAD

**Issue by newyear2580** [Mariotti94/WebRISC-V#18]
I am doing with my classmates how to use WebRISC-V to learn the pipeline datapath, and found some problems in the process.
When loading the array with some 0 value in, it will encounter a bug.
```
.data
nums:		.word 0, 1, 0, 3, 12
.text
main:
	la   s0, nums	 # s0 = nums[0]
	addi a1, x0, 3	 # a1 = len(nums)
	addi t0, x0, 0	 # t0 = i = 0
loopi:
	bge  t0, a1, end # i >= len(nums), end
	slli t1, t0, 2	 # t1: i << 2
	add  t1, t1, s0  
	lw   a0, 0(t1)   # load nums[i] to argument a0
	addi a7, x0, 1	 # print int
	ecall
	addi t0, t0, 1   # i += 1
	j    loopi
end:
```
After executing the whole program, the value we expected to print on the console should be `0, 1, 0, 3, 12`.
But in WebRISC-V, we guess that it seems to ignore the `0` value and load the next value which is not `0`. (The result show below.)
![](https://i.imgur.com/j2hcOBb.png)

**Comment by Mariotti94** [comment]
Hello, i have fixed this bug, i had filtered the input a bit too much.
Thanks for the report.

PS: The live site is not yet updated, should be updated by tomorrow (you can easily check through the version number, top left under logo).
EDIT: Site updated.
