### ISSUE TITLE
Error on Execution Table

### ISSUE THREAD

**Issue by bristalandres** [Mariotti94/WebRISC-V#19]
Hi, im getting this error: 
LOADING...
Warning: Undefined array key 374 in /var/www/html/src/pipeTable.php on line 173

Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/html/src/pipeTable.php:173 Stack trace: #0 {main} thrown in /var/www/html/src/pipeTable.php on line 173

When I try to open the execution table with my code. I attach the code that generates the problem:
[codigo_punto_5.txt](https://github.com/Mariotti94/WebRISC-V/files/8401126/codigo_punto_5.txt)

**Comment by Mariotti94** [comment]
Hello, i have fixed this bug.
Thanks for the report.

PS: The live site is not yet updated, should be updated by tomorrow (you can easily check through the version number, top left under logo).
EDIT: Site updated.

**Comment by bristalandres** [comment]
Thanks!
