### ISSUE TITLE
Local deployment process automation

### ISSUE THREAD

**Issue by HRahikainen** [Mariotti94/WebRISC-V#2]
Hi, I'm no PHP developer, but the local deployment process seems so straight forward that Docker might suit it well. A quick google search gave a couple of examples that might fit almost out of the box:

https://hub.docker.com/_/php  -> php:7.2-apache base image
https://github.com/mboyov/apache2-php7.2
https://hub.docker.com/r/mobingi/ubuntu-apache2-php7/dockerfile

I might also be able to do it once I have time and a little context to what all these packages are.

**Comment by Mariotti94** [comment]
It should be quite easy to make it run on Docker, i think.
If you want to give it a try, since i'm sort of busy these days, i can tell you that the only package WebRISC-V needs over a standard php installation is php-gmp.
