### ISSUE TITLE
Problem running a simple code

### ISSUE THREAD

**Issue by smarco** [Mariotti94/WebRISC-V#20]
Hi, 

I am running a simple code with the current web version of the simulator [https://webriscv.dii.unisi.it/index.php](https://webriscv.dii.unisi.it/index.php). I am having trouble loading the code and executing it. Could you have a quick look (this simulator is awesome)?

```
.data
N:  .word 10
V:  .word 90,50,40,20,30,10,80,70,60,100
.text
main:
li   t2, 0
la   t3, N
lw   t3, 0(t3)
la   t4, V 
addi a7, x0, 1
p1:
beq  t2, t3, end
lw   a0, 0(t4)
ecall
addi t2, t2, 1
addi t4, t4, 4
j p1
end:
```

Thank you very much for your time and assistance.

**Comment by Mariotti94** [comment]
Hello, this bug is now fixed, it was an error in the li pseudo instruction code.
Thanks for the report, let me know if you find anything else weird.

PS: The live site is not yet updated, should be updated sometimes soon (you can check through the version number).

**Comment by smarco** [comment]
Ok, thank you so much for the quick answer. 
Cannot wait for the live site to update to 1.8.2 and test it. 
It is a great tool.

**Comment by smarco** [comment]
Hi,

Sorry for bothering again. Do you have an estimate on when the live site will be updated?

Thanks,

**Comment by Mariotti94** [comment]
As my collaborator that updated the site went kind of M.I.A., i brought up an alternative website to use for now at least: [WebRISC-V](https://webriscv.altervista.org/)

**Comment by smarco** [comment]
Ah! No problem! Thanks so much for the fast response. I really appreciate it!
