### ISSUE TITLE
Support `li` pseudo-instruction

### ISSUE THREAD

**Issue by tmcintos** [Mariotti94/WebRISC-V#3]
Support `li` pseudo-instruction

`li rd, immediate`

As per Table 20.2, https://content.riscv.org/wp-content/uploads/2017/05/riscv-spec-v2.2.pdf

This would provide better compatibility with gcc-generated assembly code; e.g. https://godbolt.org/z/tTvkEE

**Comment by Mariotti94** [comment]
This pseudo-instruction has been added.
